version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/api"
      - "/metrics"
      - "/services/provider/api"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      go-deps:
        applies-to: version-updates
        group-by: dependency-name
        patterns:
          - "*"
      go-security:
        applies-to: security-updates
        group-by: dependency-name
        patterns:
          - "*"
