# This file contains all available configuration options
# with their default values.
# options for analysis running
run:

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 2m

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - unused
    - varcheck
    - gofmt
    - revive
