kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocs-metrics-exporter
rules:
- apiGroups:
  - ceph.rook.io
  resources:
  - cephobjectstores
  - cephblockpools
  - cephclusters
  - cephrbdmirrors
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - quota.openshift.io
  resources:
  - clusterresourcequotas
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - objectbucket.io
  resources:
  - objectbuckets
  verbs:
    - get
    - list
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
    - get
    - list
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
    - get
    - list
    - watch
