apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oauth-proxy-role-binding
subjects:
- kind: ServiceAccount
  name: ux-backend-server
  namespace: openshift-storage
roleRef:
  kind: ClusterRole
  name: oauth-proxy-role
  apiGroup: rbac.authorization.k8s.io
