# permissions for end users to view storageclusterpeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: storageclusterpeer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ocs-operator
    app.kubernetes.io/part-of: ocs-operator
    app.kubernetes.io/managed-by: kustomize
  name: storageclusterpeer-viewer-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageclusterpeers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageclusterpeers/status
  verbs:
  - get
