kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-k8s-cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-storage
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
