apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocs-metrics-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocs-metrics-exporter
subjects:
- kind: ServiceAccount
  name: ocs-metrics-exporter
  namespace: openshift-storage

