#!/bin/bash

# shellcheck disable=SC2034
# disable unused variable warnings

LOCALBIN="$(pwd)/bin"

GOPROXY="https://proxy.golang.org"
GOOS="${GOOS:-linux}"
GOARCH="${GOARCH:-amd64}"
GOHOSTOS="$(go env GOHOSTOS)"
GOHOSTARCH="$(go env GOHOSTARCH)"

PODMAN=$(command -v podman || echo "")
DOCKER=$(command -v docker || echo "")
CONTAINER_CLI="${CONTAINER_CLI:-${PODMAN:-${DOCKER}}}"

VERSION="${VERSION:-4.13.0}"
REPLACES_VERSION="${REPLACES_VERSION:-}"
SKIP_RANGE=">=0.0.1 <${VERSION}"
LDFLAGS="-X github.com/red-hat-storage/ocs-operator/v4/version.Version=${CSV_VERSION}"

CSV_TEMPLATES_DIR="deploy/csv-templates"
CRDS_DIR="$CSV_TEMPLATES_DIR/crds"
MANIFESTS_DIR="deploy/ocs-operator/manifests"
EXTRA_MANIFESTS_DIR="rbac"
NOOBAA_CSV="$CSV_TEMPLATES_DIR/noobaa-csv.yaml"
NOOBAA_CRDS="$CRDS_DIR/noobaa"
ROOK_CSV="$CSV_TEMPLATES_DIR/rook-csv.yaml.in"
ROOK_CRDS="$CRDS_DIR/rook"
OCS_CSV="$CSV_TEMPLATES_DIR/ocs-operator.csv.yaml.in"
OCS_CRDS="$CRDS_DIR/ocs"

DEPLOY_YAML_PATH="deploy/deploy-with-olm.yaml"

OCS_OC_PATH="${OCS_OC_PATH:-oc}"

ROOK_IMAGE="docker.io/rook/ceph:v1.12.2"
CEPH_IMAGE="quay.io/ceph/ceph:v17"
NOOBAA_IMAGE="quay.io/noobaa/noobaa-operator:master-20230718"
NOOBAA_CORE_IMAGE="quay.io/noobaa/noobaa-core:master-20230718"
NOOBAA_DB_IMAGE="centos/postgresql-12-centos8"
ROOK_CSIADDONS_IMAGE="quay.io/csiaddons/k8s-sidecar:v0.6.0"
# TODO: change image once the quay repo is changed
MUST_GATHER_IMAGE="quay.io/ocs-dev/ocs-must-gather:latest"

IMAGE_REGISTRY="${IMAGE_REGISTRY:-quay.io}"
REGISTRY_NAMESPACE="${REGISTRY_NAMESPACE:-ocs-dev}"
IMAGE_TAG="${IMAGE_TAG:-latest}"

OPERATOR_NAME="ocs-operator"
METRICS_EXPORTER_NAME="ocs-metrics-exporter"
BUNDLE_NAME="ocs-operator-bundle"
CATALOG_NAME="ocs-operator-catalog"

OPERATOR_IMAGE="${IMAGE_REGISTRY}/${REGISTRY_NAMESPACE}/${OPERATOR_NAME}:${IMAGE_TAG}"
METRICS_EXPORTER_IMAGE="${IMAGE_REGISTRY}/${REGISTRY_NAMESPACE}/${METRICS_EXPORTER_NAME}:${IMAGE_TAG}"
BUNDLE_IMAGE="${IMAGE_REGISTRY}/${REGISTRY_NAMESPACE}/${BUNDLE_NAME}:${IMAGE_TAG}"
CATALOG_IMAGE="${IMAGE_REGISTRY}/${REGISTRY_NAMESPACE}/${CATALOG_NAME}:${IMAGE_TAG}"

NOOBAA_BUNDLE_IMAGE="docker.io/noobaa/noobaa-operator-bundle:v5.13.0"

GINKGO_TEST_SUITE="${GINKGO_TEST_SUITE:-ocs}"

# This env var allows developers to point to a custom oc tool that isn't in $PATH
# defaults to just using the 'oc' binary provided in $PATH
OCS_OC_PATH="${OCS_OC_PATH:-oc}"
OCS_FINAL_DIR="deploy/ocs-operator/manifests"
BUNDLEMANIFESTS_DIR="rbac"

NOOBAA_CSV="$OUTDIR_TEMPLATES/noobaa-csv.yaml"
ROOK_CSV="$OUTDIR_TEMPLATES/rook-csv.yaml.in"
OCS_CSV="$OUTDIR_TEMPLATES/ocs-operator.csv.yaml.in"

LATEST_ROOK_IMAGE="docker.io/rook/ceph:v1.12.2"
LATEST_NOOBAA_IMAGE="quay.io/noobaa/noobaa-operator:master-20230718"
LATEST_NOOBAA_CORE_IMAGE="quay.io/noobaa/noobaa-core:master-20230718"
LATEST_NOOBAA_DB_IMAGE="docker.io/centos/postgresql-12-centos8"
LATEST_CEPH_IMAGE="quay.io/ceph/ceph:v17"
LATEST_ROOK_CSIADDONS_IMAGE="quay.io/csiaddons/k8s-sidecar:v0.6.0"
# TODO: change image once the quay repo is changed
LATEST_MUST_GATHER_IMAGE="quay.io/ocs-dev/ocs-must-gather:latest"

DEFAULT_IMAGE_REGISTRY="quay.io"
DEFAULT_REGISTRY_NAMESPACE="ocs-dev"
DEFAULT_IMAGE_TAG="latest"
DEFAULT_OPERATOR_IMAGE_NAME="ocs-operator"
DEFAULT_OPERATOR_BUNDLE_NAME="ocs-operator-bundle"
DEFAULT_FILE_BASED_CATALOG_NAME="ocs-operator-catalog"
DEFAULT_METRICS_EXPORTER_IMAGE_NAME="ocs-metrics-exporter"

IMAGE_REGISTRY="${IMAGE_REGISTRY:-${DEFAULT_IMAGE_REGISTRY}}"
REGISTRY_NAMESPACE="${REGISTRY_NAMESPACE:-${DEFAULT_REGISTRY_NAMESPACE}}"
OPERATOR_IMAGE_NAME="${OPERATOR_IMAGE_NAME:-${DEFAULT_OPERATOR_IMAGE_NAME}}"
OPERATOR_BUNDLE_NAME="${OPERATOR_BUNDLE_NAME:-${DEFAULT_OPERATOR_BUNDLE_NAME}}"
FILE_BASED_CATALOG_NAME="${FILE_BASED_CATALOG_NAME:-${DEFAULT_FILE_BASED_CATALOG_NAME}}"
METRICS_EXPORTER_IMAGE_NAME="${METRICS_EXPORTER_IMAGE_NAME:-${DEFAULT_METRICS_EXPORTER_IMAGE_NAME}}"
IMAGE_TAG="${IMAGE_TAG:-${DEFAULT_IMAGE_TAG}}"

DEFAULT_OPERATOR_FULL_IMAGE_NAME="${IMAGE_REGISTRY}/${REGISTRY_NAMESPACE}/${OPERATOR_IMAGE_NAME}:${IMAGE_TAG}"
DEFAULT_BUNDLE_FULL_IMAGE_NAME="${IMAGE_REGISTRY}/${REGISTRY_NAMESPACE}/${OPERATOR_BUNDLE_NAME}:${IMAGE_TAG}"
DEFAULT_FILE_BASED_CATALOG_FULL_IMAGE_NAME="${IMAGE_REGISTRY}/${REGISTRY_NAMESPACE}/${FILE_BASED_CATALOG_NAME}:${IMAGE_TAG}"
DEFAULT_METRICS_EXPORTER_FULL_IMAGE_NAME="${IMAGE_REGISTRY}/${REGISTRY_NAMESPACE}/${METRICS_EXPORTER_IMAGE_NAME}:${IMAGE_TAG}"

OPERATOR_FULL_IMAGE_NAME="${OPERATOR_FULL_IMAGE_NAME:-${DEFAULT_OPERATOR_FULL_IMAGE_NAME}}"
BUNDLE_FULL_IMAGE_NAME="${BUNDLE_FULL_IMAGE_NAME:-${DEFAULT_BUNDLE_FULL_IMAGE_NAME}}"
FILE_BASED_CATALOG_FULL_IMAGE_NAME="${FILE_BASED_CATALOG_FULL_IMAGE_NAME:-${DEFAULT_FILE_BASED_CATALOG_FULL_IMAGE_NAME}}"
METRICS_EXPORTER_FULL_IMAGE_NAME="${METRICS_EXPORTER_FULL_IMAGE_NAME:-${DEFAULT_METRICS_EXPORTER_FULL_IMAGE_NAME}}"

NOOBAA_BUNDLE_FULL_IMAGE_NAME="quay.io/noobaa/noobaa-operator-bundle:master-20230718"

OCS_OPERATOR_INSTALL="${OCS_OPERATOR_INSTALL:-false}"
OCS_CLUSTER_UNINSTALL="${OCS_CLUSTER_UNINSTALL:-false}"
OCS_SUBSCRIPTION_CHANNEL=${OCS_SUBSCRIPTION_CHANNEL:-alpha}
INSTALL_NAMESPACE="${INSTALL_NAMESPACE:-openshift-storage}"
OCS_OPERATOR_INSTALL="${OCS_OPERATOR_INSTALL:-false}"
OCS_CLUSTER_UNINSTALL="${OCS_CLUSTER_UNINSTALL:-false}"

OCS_MUST_GATHER_DIR="${OCS_MUST_GATHER_DIR:-ocs-must-gather}"
OCP_MUST_GATHER_DIR="${OCP_MUST_GATHER_DIR:-ocp-must-gather}"


PROTOC_VERSION="3.20.0"
PROTOC_GEN_GO_VERSION="1.26.0"
PROTOC_GEN_GO_GRPC_VERSION="1.1.0"

GRPC_BIN="${LOCALBIN}/grpc"
PROTOC="${GRPC_BIN}/protoc"
PROTO_GOOGLE="${GRPC_BIN}/google/protobuf"
PROTOC_GEN_GO="${GRPC_BIN}/protoc-gen-go"
PROTOC_GEN_GO_GRPC="${GRPC_BIN}/protoc-gen-go-grpc"

# gRPC services
SERVICES=("provider")

OPERATOR_SDK_VERSION="v1.25.4"
OPERATOR_SDK="${LOCALBIN}/operator-sdk-${OPERATOR_SDK_VERSION}"

OPM_VERSION="v1.28.0"
OPM="${LOCALBIN}/opm-${OPM_VERSION}"

GOLANGCI_LINT_VERSION="v1.51.1"
GOLANGCI_LINT="${LOCALBIN}/golangci-lint"

SHELLCHECK="${LOCALBIN}/shellcheck"
SHELLCHECK_VERSION="v0.9.0"

GINKGO="${LOCALBIN}/ginkgo"
