# Build options
IMG_BUILD_CMD ?= docker
TARGET_OS ?= linux
TARGET_ARCH ?= amd64

# Tools versions
OPM_VERSION ?= v1.26.0

# Tools paths
OUTDIR ?= build/_output
OUTDIR_TOOLS= ${OUTDIR}/tools
OPM ?= ${OUTDIR_TOOLS}/opm-${OPM_VERSION}

# Image name vars
IMG_REGISTRY ?= quay.io
REGISTRY_NAMESPACE ?= ocs-dev
IMG_TAG ?= latest

OCS_OPERATOR_IMG_NAME ?= ocs-operator
OCS_METRICS_EXPORTER_IMG_NAME ?= ocs-metrics-exporter
OCS_MUST_GATHER_IMG_NAME ?= ocs-must-gather

OCS_BUNDLE_IMG_NAME ?= ocs-operator-bundle
OCS_CATALOG_IMG_NAME ?= ocs-operator-catalog

OCS_OPERATOR_IMG ?= ${IMG_REGISTRY}/${REGISTRY_NAMESPACE}/${OCS_OPERATOR_IMG_NAME}:${IMG_TAG}
OCS_METRICS_EXPORTER_IMG ?= ${IMG_REGISTRY}/${REGISTRY_NAMESPACE}/${OCS_METRICS_EXPORTER_IMG_NAME}:${IMG_TAG}
OCS_MUST_GATHER_IMG ?= ${IMG_REGISTRY}/${REGISTRY_NAMESPACE}/${OCS_MUST_GATHER_IMG_NAME}:${IMG_TAG}

OCS_BUNDLE_IMG ?= ${IMG_REGISTRY}/${REGISTRY_NAMESPACE}/${OCS_BUNDLE_IMG_NAME}:${IMG_TAG}
OCS_CATALOG_IMG ?= ${IMG_REGISTRY}/${REGISTRY_NAMESPACE}/${OCS_CATALOG_IMG_NAME}:${IMG_TAG}

NOOBAA_BUNDLE_IMG ?= quay.io/noobaa/noobaa-operator-bundle:v5.12.0
