apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocs-devicefinder-use-privileged-scc
rules:
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames: ["privileged"]
  verbs: ["use"]
