apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocs-operator-networkpolicy
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - update
  - delete
