kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocs-provider-server
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - get
- apiGroups:
  - ceph.rook.io
  resources:
  - cephfilesystemsubvolumegroups
  verbs:
  - get
  - list
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageconsumers
  - storageconsumers/finalizers
  - storageconsumers/status
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - patch
- apiGroups:
  - ceph.rook.io
  resources:
  - cephclients
  verbs:
  - get
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageclassclaims
  verbs:
  - get
  - list
  - create
  - delete
