kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ux-backend-server
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - onboarding-private-key
  - ux-cert-secret
  - ux-backend-proxy
  verbs:
    - get
    - list
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageclusters
  verbs:
  - get
  - list
  - update
- apiGroups:
  - ceph.rook.io
  resources:
  - cephblockpools
  verbs:
  - create
- apiGroups:
  - noobaa.io
  resources:
  - noobaas
  verbs:
  - get
  - list
