#!/bin/bash

BASE_COLLECTION_PATH="/must-gather"
INSPECT_CLI="oc adm --dest-dir"
if [ "${INSPECT_CLIENT}" = "openshift-must-gather" ];then
    INSPECT_CLI="openshift-must-gather --base-dir"
fi



# TODO: Resources commnon to both noobaa and ceph can be collected here

# Resource List
resources=()

# collect OB/OBC resoureces
resources+=(objectbucketclaims)
resources+=(objectbuckets)

# Add general resources to list if necessary 

# Run the Collection of Resources using must-gather
for resource in ${resources[@]}; do
    ${INSPECT_CLI}=${BASE_COLLECTION_PATH} inspect ${resource} --all-namespaces
done

# Call other gather scripts
gather_noobaa_resources ${BASE_COLLECTION_PATH}
gather_ceph_resources ${BASE_COLLECTION_PATH}

exit 0