#!/bin/bash
# Expect base collection path as an argument
BASE_COLLECTION_PATH=$1

# Use PWD as base path if no argument is passed
if [ "${BASE_COLLECTION_PATH}" = "" ]; then
    BASE_COLLECTION_PATH=$(pwd)
fi

# Command List
commands=()

# collect oc output of OC get commands
commands+=("get pv")
commands+=("get sc")


# Run the Collection of Resources to list
for command in "${commands[@]}"; do
     echo "collecting oc command ${command}" | tee -a ${BASE_COLLECTION_PATH}/gather-debug.log
     COMMAND_OUTPUT_FILE=${BASE_COLLECTION_PATH}/oc_output/${command// /_}
     # shellcheck disable=SC2086
     timeout 120 oc ${command} >> "${COMMAND_OUTPUT_FILE}"
done

{ oc adm --dest-dir="${BASE_COLLECTION_PATH}" inspect pv --all-namespaces; } >> "${BASE_COLLECTION_PATH}"/gather-debug.log 2>&1
{ oc adm --dest-dir="${BASE_COLLECTION_PATH}" inspect sc -n openshift-storage; } >> "${BASE_COLLECTION_PATH}"/gather-debug.log 2>&1
